/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcSearchRouteImport } from './routes/upc-search'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScannerResultsRouteImport } from './routes/scanner-results'
import { Route as ScannerDemoRouteImport } from './routes/scanner-demo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClipRouteImport } from './routes/clip'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UpcSearchRoute = UpcSearchRouteImport.update({
  id: '/upc-search',
  path: '/upc-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerResultsRoute = ScannerResultsRouteImport.update({
  id: '/scanner-results',
  path: '/scanner-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerDemoRoute = ScannerDemoRouteImport.update({
  id: '/scanner-demo',
  path: '/scanner-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipRoute = ClipRouteImport.update({
  id: '/clip',
  path: '/clip',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/catalog': typeof CatalogRoute
  '/clip': typeof ClipRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/scanner-results': typeof ScannerResultsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/thankyou': typeof ThankyouRoute
  '/upc-search': typeof UpcSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/catalog': typeof CatalogRoute
  '/clip': typeof ClipRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/scanner-results': typeof ScannerResultsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/thankyou': typeof ThankyouRoute
  '/upc-search': typeof UpcSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/catalog': typeof CatalogRoute
  '/clip': typeof ClipRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/scanner-demo': typeof ScannerDemoRoute
  '/scanner-results': typeof ScannerResultsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/thankyou': typeof ThankyouRoute
  '/upc-search': typeof UpcSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/catalog'
    | '/clip'
    | '/dashboard'
    | '/privacy'
    | '/scanner-demo'
    | '/scanner-results'
    | '/sign-in'
    | '/sign-up'
    | '/thankyou'
    | '/upc-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/catalog'
    | '/clip'
    | '/dashboard'
    | '/privacy'
    | '/scanner-demo'
    | '/scanner-results'
    | '/sign-in'
    | '/sign-up'
    | '/thankyou'
    | '/upc-search'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-keys'
    | '/catalog'
    | '/clip'
    | '/dashboard'
    | '/privacy'
    | '/scanner-demo'
    | '/scanner-results'
    | '/sign-in'
    | '/sign-up'
    | '/thankyou'
    | '/upc-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiKeysRoute: typeof ApiKeysRoute
  CatalogRoute: typeof CatalogRoute
  ClipRoute: typeof ClipRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ScannerDemoRoute: typeof ScannerDemoRoute
  ScannerResultsRoute: typeof ScannerResultsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ThankyouRoute: typeof ThankyouRoute
  UpcSearchRoute: typeof UpcSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upc-search': {
      id: '/upc-search'
      path: '/upc-search'
      fullPath: '/upc-search'
      preLoaderRoute: typeof UpcSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner-results': {
      id: '/scanner-results'
      path: '/scanner-results'
      fullPath: '/scanner-results'
      preLoaderRoute: typeof ScannerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner-demo': {
      id: '/scanner-demo'
      path: '/scanner-demo'
      fullPath: '/scanner-demo'
      preLoaderRoute: typeof ScannerDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip': {
      id: '/clip'
      path: '/clip'
      fullPath: '/clip'
      preLoaderRoute: typeof ClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiKeysRoute: ApiKeysRoute,
  CatalogRoute: CatalogRoute,
  ClipRoute: ClipRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  ScannerDemoRoute: ScannerDemoRoute,
  ScannerResultsRoute: ScannerResultsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ThankyouRoute: ThankyouRoute,
  UpcSearchRoute: UpcSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
